[build]
  command = "NODE_OPTIONS='--max-old-space-size=4096' pnpm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20"
  HUSKY = "0"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@remix-run/node", "@remix-run/react", "react", "react-dom"]

